apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kubectl-client
  namespace: default
rules:
- apiGroups:
  - ""
  - apps
  - rbac.authorization.k8s.io
  resources:
  - pods
  - deployments
  - roles
  - serviceaccounts
  verbs:
  - create
  - delete
  - update
  - patch
  - get
  - list
  - watch
